plugins {
    id "com.android.application"
}

android {
    enableKotlin = false
    namespace "org.harp.l2"
    compileSdk 36

    defaultConfig {
        applicationId "org.harp.l2"
        minSdk 29
        targetSdk 36
        versionCode 3
        versionName "0.3-stage01"
    }

    buildTypes {
        debug {
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}


def hevAar = file("libs/hev-socks5-tunnel.aar")

dependencies {
    if (hevAar.exists()) {
        implementation files(hevAar)
    }
}
